### ISSUE TITLE
Modifying Proguard 

### ISSUE THREAD

**Issue by TirelessMan** [dweiss/proguard#1]
Hi, 
I am going to add some new features to Proguard project, For example I want to add some DexGuard Features to Proguard, Some of them that are not support by Progurad by default.
My question is that can I really modify Progurad source code and add my features?
And If yes, Dose this work is a very trivial or hard proceess?
Thanks in advance

**Comment by dweiss** [comment]
You should ask on ProGuard's tracker, this is a fork.

**Comment by TirelessMan** [comment]
I can not find ProGuard tracker :(
